### ISSUE TITLE
npm run demo0* Error

### ISSUE THREAD

**Issue by XiaoLiz** [ruanyf/css-modules-demos#2]
vents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:84:10)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "demo01"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! css-modules-demos@1.0.0 demo01: `webpack-dev-server --config demo01/webpack.config.js --content-base demo01`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the css-modules-demos@1.0.0 demo01 script 'webpack-dev-server --config demo01/webpack.config.js --content-base demo01'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the css-modules-demos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config demo01/webpack.config.js --content-base demo01
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs css-modules-demos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls css-modules-demos
npm ERR! There is likely additional logging output above.

Seemingly port occupied, to solve the method

**Comment by ruanyf** [comment]
报错信息里面不是说了吗，端口被占用了。

Seemingly port occupied, to solve the method

**Comment by XiaoLiz** [comment]
Excuse me,  thank you!
